
--CREAMOS LAS TABLAS DE DATOS

--TABLA PARA EL EMPLEADO
CREATE TABLE EMPLEADO (
RUT CHAR(10) NOT NULL ,
NOMBRE VARCHAR2(30)NOT NULL ,
FECHA_DE_CONTRATACION DATE NOT NULL,
FECHA_DE_NACIMIENTO DATE NOT NULL,
DIRECCION VARCHAR2(30),
--LLAVE PRIMARIA
CONSTRAINT PK_RUT
PRIMARY KEY (RUT)
);


--TABLA PARA EL PROYECTO
CREATE TABLE PROYECTO (
CODIGO CHAR(5) NOT NULL,
NOMBRE VARCHAR2(30)NOT NULL,
FECHA_DE_INICIO DATE NOT NULL,
FECHA_DE_TERMINO DATE NOT NULL,
PRESUPUESTO NUMBER(8,2),
TIPO_PROYECTO CHAR(1),
RUT_JEFE CHAR(10) NOT NULL,
--RESTRICCIONES
CHECK(TIPO_PROYECTO LIKE '[A,B,C,D,X,Y,Z]'),
CHECK(FECHA_DE_INICIO > TO_DATE('2000-01-01','YYYY-MM-DD')),
CHECK(FECHA_DE_INICIO < FECHA_DE_TERMINO),
--LLAVE PRIMARIA
CONSTRAINT PK_CODIGO
PRIMARY KEY (CODIGO)
);

--CREAMOS LA CLAVE FORANEA
ALTER TABLE PROYECTO 
ADD CONSTRAINT FK_RUT_JEFE FOREIGN KEY (RUT_JEFE) REFERENCES EMPLEADO(RUT);

--TABLA PARA EL EMPLEADO DEL PROYECTO
CREATE TABLE  EMP_PROY (
RUT_EMP_PROY CHAR(10) NOT NULL ,
CODIGO_EMP_PROY CHAR(5) NOT NULL ,
HORAS CHAR(2) NOT NULL,
--RESTRICCIONES
CHECK(HORAS > 5 AND HORAS < 22),
--LLAVE PRIMARIA
CONSTRAINT PK_CODIGO_RUT
PRIMARY KEY (RUT_EMP_PROY,CODIGO_EMP_PROY)
);
--CREAMOS LA CLAVE FORANEA
ALTER TABLE PROYECTO 
ADD CONSTRAINT FK_RUT_EMP_PROY FOREIGN KEY (RUT_EMP_PROY) REFERENCES EMPLEADO(RUT);
ALTER TABLE PROYECTO 
ADD CONSTRAINT FK_CODIGO_EMP_PROY FOREIGN KEY (CODIGO_EMP_PROY) REFERENCES PROYECTO(CODIGO);

SELECT * FROM EMPLEADO


