--TABLA PARA EL EMPLEADO

CREATE TABLE EMPLEADO 
(
  RUT NUMBER(10, 0) NOT NULL 
, NOMBRE VARCHAR2(30) NOT NULL 
, FECHA_DE_CONTRATACION DATE NOT NULL 
, FECHA_DE_NACIMIENTO DATE NOT NULL 
, DIRECCION VARCHAR2(30) 
, CONSTRAINT EMPLEADO_PK PRIMARY KEY 
  (
    RUT 
  )
 ENABLE
);

--TABLA PARA EL PROYECTO
CREATE TABLE PROYECTO 
(
  CODIGO NUMBER(5,0) NOT NULL 
, NOMBRE VARCHAR2(30) NOT NULL 
, FECHA_DE_INICIO DATE NOT NULL 
, FECHA_DE_TERMINO DATE NOT NULL 
, PRESUPUESTO NUMBER(8, 2) DEFAULT 0 
, TIPO_PROYECTO VARCHAR2(1) 
, RUT_JEFE NUMBER(10, 0) NOT NULL 
, CONSTRAINT PROYECTO_PK PRIMARY KEY 
  (
    CODIGO 
  )
  ENABLE 
);

CREATE SEQUENCE PROYECTO_SEQ;

CREATE TRIGGER PROYECTO_TRG 
BEFORE INSERT ON PROYECTO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CODIGO IS NULL THEN
      SELECT PROYECTO_SEQ.NEXTVAL INTO :NEW.CODIGO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/


--TABLA PARA EL EMPLEADO DEL PROYECTO
CREATE TABLE EMP_PROY 
(
  RUT NUMBER(10) NOT NULL 
, CODIGO NUMBER(5) NOT NULL 
, HORAS NUMBER(2) NOT NULL 
, CONSTRAINT EMP_PROY_PK PRIMARY KEY 
  (
    RUT 
  , CODIGO 
  )
  ENABLE 
);
