--TABLA PARA EL EMPLEADO

CREATE TABLE Empleado (
RUT CHAR(10) NOT NULL ,
NOMBRE VARCHAR2(30)NOT NULL ,
FECHA_DE_CONTRATACION DATE NOT NULL,
FECHA_DE_NACIMIENTO DATE NOT NULL,
DIRECCION VARCHAR2(30),
CONSTRAINT PK_RUT
PRIMARY KEY (RUT)
);


--TABLA PARA EL PROYECTO
CREATE TABLE PROYECTO (
CODIGO CHAR(5) NOT NULL ,
NOMBRE VARCHAR2(30)NOT NULL,
FECHA_DE_INICIO DATE NOT NULL,
FECHA_DE_TERMINO DATE NOT NULL,
PRESUPUESTO VARCHAR2(8),
TIPO_PROYECTO CHAR(1),
RUT_JEFE CHAR(10) NOT NULL,
CONSTRAINT PK_CODIGO
PRIMARY KEY (CODIGO)
);

--TABLA PARA EL EMPLEADO DEL PROYECTO
CREATE TABLE EMP_PROY (
RUT CHAR(10) NOT NULL,
CODIGO CHAR(5) NOT NULL ,
HORAS CHAR(2) NOT NULL,
CONSTRAINT PK_CODIGO_RUT
PRIMARY KEY (RUT,CODIGO)
);


